### ISSUE TITLE
About 'Training'

### ISSUE THREAD

**Issue by jjayun** [faresbs/slrt#1]
May I ask you about this error?

I'd appreciate it if you could let me know.

$ python train_slr.py

```
Start Time: 2021-03-09-21.23

Putting log in EXPERIMENTATIONS/2021-03-09-21.23
Training  CNN-attention-CTC  on GPU!
Dataset sizes:
{'train': 5672, 'valid': 540}
vocabulary size:1233
None
False
False
False

Training using 1.py device (GPU/CPU), use very small batch_size!
Loading to GPUs
| ID | GPU | MEM |
------------------
|  0 |  3% | 15% |
|  1 |  0% |  0% |
None
No scheduler!

EPOCH 0 ------------------
After train epoch..
| ID | GPU | MEM |
------------------
|  0 |  3% | 15% |
|  1 |  0% |  0% |
None
Evaluating..
Traceback (most recent call last):
  File "/home/jygim/Workspace/SAN/train_slr.py", line 642, in <module>
    val_loss, word_err = run_epoch(model, valid_dataloader)
  File "/home/jygim/Workspace/SAN/train_slr.py", line 261, in run_epoch
    for step, (x, x_lengths, y, y_lengths, hand_regions, hand_lengths) in enumerate(data):
  File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jygim/Workspace/SAN/dataloader_slr.py", line 180, in __getitem__
    sample = {'images': trsf_images, 'right_hands':hand_images, 'translation': trans}
UnboundLocalError: local variable 'trsf_images' referenced before assignment

```

**Comment by kkk241-q** [comment]
> 我可以问你这个错误吗？
> 
> 如果您能告诉我，我将不胜感激。
> 
> $ python train_slr.py
> 
> ```
> Start Time: 2021-03-09-21.23
> 
> Putting log in EXPERIMENTATIONS/2021-03-09-21.23
> Training  CNN-attention-CTC  on GPU!
> Dataset sizes:
> {'train': 5672, 'valid': 540}
> vocabulary size:1233
> None
> False
> False
> False
> 
> Training using 1.py device (GPU/CPU), use very small batch_size!
> Loading to GPUs
> | ID | GPU | MEM |
> ------------------
> |  0 |  3% | 15% |
> |  1 |  0% |  0% |
> None
> No scheduler!
> 
> EPOCH 0 ------------------
> After train epoch..
> | ID | GPU | MEM |
> ------------------
> |  0 |  3% | 15% |
> |  1 |  0% |  0% |
> None
> Evaluating..
> Traceback (most recent call last):
>   File "/home/jygim/Workspace/SAN/train_slr.py", line 642, in <module>
>     val_loss, word_err = run_epoch(model, valid_dataloader)
>   File "/home/jygim/Workspace/SAN/train_slr.py", line 261, in run_epoch
>     for step, (x, x_lengths, y, y_lengths, hand_regions, hand_lengths) in enumerate(data):
>   File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
>     data = self._next_data()
>   File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
>     return self._process_data(data)
>   File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
>     data.reraise()
>   File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
>     raise self.exc_type(msg)
> UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/jygim/miniconda3/envs/san/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/jygim/Workspace/SAN/dataloader_slr.py", line 180, in __getitem__
>     sample = {'images': trsf_images, 'right_hands':hand_images, 'translation': trans}
> UnboundLocalError: local variable 'trsf_images' referenced before assignment
> ```

How did you solve this problem? I have a similar problem
