### ISSUE TITLE
about running

### ISSUE THREAD

**Issue by YePG** [faresbs/slrt#2]
running  python evalaute_slr.py   this step
it will have a error,your code is
from transformer_slr_wassim import make_model as TRANSFORMER
from dataloader_slr_wassim import loader #For SLR

but your filename is transformer_slr and dataloader_slr

**Comment by faresbs** [comment]
I am very sorry for the late response. I am aware of these type of problems that have been produced after migrating the code. I was busy  lately with work so i didn't have time to clean and fix the code errors. Hopefully in the next few weeks i will get back to it. 
Thank you for your understanding :)
