### ISSUE TITLE
cannot find pickle file

### ISSUE THREAD

**Issue by tsubameOPU** [faresbs/slrt#3]
I am trying to run keyframes2.py.
But I got error of wordFrameLabelPerVideo.pickle.
I cannot find this file.
Could you share  wordFrameLabelPerVideo.pickle??

**Comment by faresbs** [comment]
I am very sorry for the late response. I am aware of the problem of missing files. I was busy  lately with work so i didn't have time to clean and fix the code errors. Hopefully in the next few weeks i will get back to it. 
Thank you for your understanding :)
